language: c
sudo: required
services:
- docker
before_install:
- docker pull ubuntu:16.04
script:
- docker build -t my_image .
- docker create --name my_container my_image
- docker cp my_container:/osg/releases .
- git add .
- git commit -m "Deploy"
deploy:
  provider: releases
  api_key:
    secure: Knd42yjtkIEZ3Kw/Y610wwFwx4BBfzQzbJSkGLU9BzIXv/Z5MPH/iO14SmtR2Kbqtzu+v0HQJaEdjbjeNBBDV2oDAAfIS0cZW3wYqUkBca9t2O86R5spdWha4lm6LyETiA15hVnLgpbmdZSke/KNFU210W54M72BvTNmcbtQrK4W9POtTpxWcpwGBYv8z2NF1N/wBELO4/4sTt8RkkQOjd6D6XAZNyz8029Q1tiwXawhio5jCnzR+CjWQvqyyXf5katlgq6JgX5maaMYi8tS0K4PydQxn6GKO1MwllYethdAxGfXAG3ErBagOYEW5pce2tG2uSgy8j+sVIgTd7G9CLa2OaX9cSUS3vW7sSJ31eCb9pB9tD0eXesHoSsg2CokpP+/KdgzQBSblGtTNUyKH9vo9leNwEbLelH8SVmwGvpydsuYLOWrMu3yvS5yXGQgEI+SvoSY1QRKYiuV8rDeiUkhmymGEeV/95d7SUR7g5CDSt1LYSKx9mZ52OSPVQXCkgvWWbr68lJIAVqkXpAQQc8i+1CwMHh0vEawFqn4zfqdM7McuU1F+g9hFoYxsUeo6k7mABQiOUvg6uZK6yojohSo3vbkdCZKOv0LEFmzrCbGbS7oV5zZfB2Ar0UgrWF5gX1cGtmm/6nYXcYw6ANwplZx/DLqqYVGtaKbhYa1d4k=
  file_glob: true
  skip_cleanup: true
  file: releases/*
  on:
    repo: tybantarnusa/open-snake-game
    all_branches: true
